# Generated by Django 4.0.3 on 2022-04-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
